// Create the scrape_history table

// Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- Create the scrape_history table
create table public.scrape_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  urls jsonb not null,
  image_count integer not null,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.scrape_history enable row level security;

-- Create policy for users to select their own scrape history
create policy "Users can view their own scrape history"
  on public.scrape_history
  for select
  using (auth.uid() = user_id);

-- Create policy for users to insert their own scrape history
create policy "Users can insert their own scrape history"
  on public.scrape_history
  for insert
  with check (auth.uid() = user_id);

-- Create an index on user_id for faster queries
create index idx_scrape_history_user_id on public.scrape_history(user_id);

-- Create an index on created_at for sorting
create index idx_scrape_history_created_at on public.scrape_history(created_at desc);

-- Allow authenticated users to access the table
grant select, insert on public.scrape_history to authenticated;
